language: node_js
cache: yarn
node_js:
  - "8"
install: 
  - yarn
before_script:
  - yarn build-test
script:
  - yarn coverage
after_success:
  - cat ./coverage/lcov.info | ./node_modules/coveralls/bin/coveralls.js && rm -rf ./coverage
  